### ISSUE TITLE
Can't generate Devices Token

### ISSUE THREAD

**Issue by slntopp** [infinimesh/infinimesh#607]
Error:
```
index-RRX87RO1.js:538 Uncaught (in promise) ConnectError: [internal] cannot encode field infinimesh.node.DevicesTokenRequest.post to JSON
    at ct.from (index-RRX87RO1.js:538:16929)
    at serialize (index-RRX87RO1.js:538:20727)
    at next (index-RRX87RO1.js:538:26820)
    at index-RRX87RO1.js:538:29340
    at index-RRX87RO1.js:538:29304
    at AO (index-RRX87RO1.js:538:24260)
    at Object.unary (index-RRX87RO1.js:538:26417)
    at Object.makeDevicesToken (namespaces-BFc8eTMZ.js:1:9078)
    at Proxy.makeDevicesToken (devices-QoYv0raY.js:1:1916)
    at Proxy.<anonymous> (index-RRX87RO1.js:537:2249)
```

**Comment by slntopp** [comment]
> QA: Couldn't test PatchDesired and Subscribe
